name: Pylint 
on: push

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip;
          pip install pylint;
          sudo apt-get install git
      - name: Clone BME280
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'robert-hh'
          repository: 'BME280'
      - name: Analyze code with Pylint
        run:
          pylint wpicow/*.py
          
